### ISSUE TITLE
Object Handling

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/GeometryToolkit#1]
Find a good way to store and retrieve user-created objects

**Comment by UnsolvedCypher** [comment]
Do you mean between runs of the program (ie. on the hard drive) or during runtime?

**Comment by Stefan4472** [comment]
Actually, both. I think I have found a solution though, which involves
storing all objects in an arraylist of objects. There will be a
"getObject(String object_name)" method which will search through this
array, find the correct object, and return it. Each class will also have
"writeObjectToString" and "getObjectFromString" methods for easy
reading/writing of settings files.

**Comment by Stefan4472** [comment]
I think this has been coded to a good enough extent that it can be closed for now. However, we will be constantly looking for ways to improve and streamline it as we continue development.
