### ISSUE TITLE
Better Command Syntax

### ISSUE THREAD

**Issue by Stefan4472** [Plain-Simple/GeometryToolkit#2]

**Comment by UnsolvedCypher** [comment]
I would recommend that you create a text file that has the specifications for how a syntax should work, that way you can work out everything before you start coding and not have to throw out code if you realize something later.

**Comment by Stefan4472** [comment]
Actually I have the syntax written out on a piece of paper and have planned
out how I will implement it.

**Comment by Stefan4472** [comment]
It isn't perfect yet but I think good enough to close 0.1
Again, we will continue streamlining syntax as we go.
